#JPA
spring.datasource.name=postgres
spring.datasource.password=1234
spring.datasource.url=jdbc:postgresql://localhost:5439/laperfume

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logs
logging.level.com.abraao.archivist.log=DEBUG